version: "3.7"

services:
  go-backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - 8080:8080
    depends_on:
      - postgres
    networks:
      - itonet
    
  postgres:
    image: postgres:12
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - ./db/db.sql:/docker-entrypoint-initdb.d/db.sql
      - dbvol:/var/lib/postgresql/data
    networks:
      - itonet
    restart: always
  
networks:
  itonet:

volumes:
  dbvol: